### ISSUE TITLE
How 2 make virus pls

### ISSUE THREAD

**Issue by Shaun2h** [Shaun2h/WeDoAThing#10]
hi i am sad lonely person. Please teach on how 2 make internally disruptive program. Very simple, only need portscan and disrupt non essential system ports. 

Assume program can be run with administrative rights.

Methyl said to do a forkbomb but then Poggers Prof  (he is still livestreaming cuz not dead yet) said make it less obvious.
🐞 🐞 🐞 🐞 🐞 🐞 🐞 🐞 P!!! 🐞 🐞 🐞 🐞 🐞 🐞 🐞 🐞 
![image](https://user-images.githubusercontent.com/32790402/73334400-8e254400-42a7-11ea-8e98-f1ad16b1efc4.png)

**Comment by junqingchang** [comment]
Making viruses are illegal. Please refrain from doing such things.

**Comment by Shaun2h** [comment]
P!!!! NED FOR reSEARCH

**Comment by Shaun2h** [comment]
Information dump so far:
Trusted sources of information:
volatility.exe --profile=Win2012R2x64 -f temp.raw netscan --> All open ports. High number of duplicate ports are detected by volatility, dump process takes approximately 20 seconds making it relatively unrealistic for realtime detection but it's usable i suppose considering one assumption appears to be high processing power in the future. Dumps are taken live btw.

System calls from memory dump extracted after processing:
Steps = virsh dump wireshark "${wiresharkfilenames}_${wiresharks}.windump" --verbose --memory-only
./volatility --profile=Win2012R2x64 imagecopy -O temp_$z.raw -f "${x}_$z.windump"
./volatility --profile=Win2012R2x64 raw2dmp -f temp_$z.raw -O "${y}/${x}_$z.dmp"

That converts to a dump for you in windows, but a lot of page files and the sort are missing
That's QEMU and Virtual Machine Manager on Ubuntu's side, and because we don't get to buy this kind of items like proper vm 🌵 .


Untrusted: 🥇 
netstat -a -b --> all ports and connections that are outgoing
REGEDIT /E C:\output.reg -->this literally dumps the registry files. can be used to check for edits.
Of note is that USBsTor registry entries can be especially useful for detecting a plugin or non plugin
Procmon .pml files from their trace, constantly exported
SSH log exported
All commands, sudo or not by each user.

**Comment by Shaun2h** [comment]
Forgot to mention that you need to !wow64exts.sw at the start of the generated .dmp file in windbg to change contexts
All active heaps or stacks are missing.
You will also likely use the following to extract what little you can (not exactly the most useful. The most useful are system calls. Memory addresses should change between reboots. So the best case scenario for our dump taking is to constantly reboot the device and re run all applications again. This is time consuming however.
!for_each_thread  ".thread @#Thread ; k"\n
!process 0 1
!address
.tlist
!vm
!sysinfo cpuinfo
!sysinfo machineid
