### ISSUE TITLE
Architecture for new model

### ISSUE THREAD

**Issue by Shaun2h** [Shaun2h/WeDoAThing#7]
If we can't get the WGAN to work, styleGAN is out of the question.

Currently mode collapses VERY VERY FAST.
Testing with gradient penalty right now 🌵 
@junqingchang please read this useless opened issue :c

**Comment by junqingchang** [comment]
Deeper Model in #8

**Comment by Shaun2h** [comment]
Collapsed to 0.500 instantly. Retrying.
Will check for res problem in a bit
